/**
 * Turns data/ilogic-fragments.md into the two artifacts the extension ships:
 * a VS Code snippet file and a completion member table.
 *
 * Both outputs are committed, so `npm run generate` producing a diff is the
 * signal that the fragment library changed. `npm run verify` fails if they
 * are stale.
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { parseFragments, toSnippets, toMemberTable, API_ROOTS, Member } from "./fragments";

const ROOT = path.join(__dirname, "..", "..");
const SOURCE = path.join(ROOT, "data", "ilogic-fragments.md");
const SNIPPETS_OUT = path.join(ROOT, "snippets", "ilogic.code-snippets");
const MEMBERS_OUT = path.join(ROOT, "src", "generated", "members.ts");

const BANNER = "Generated by scripts/generate.ts from data/ilogic-fragments.md. Do not edit.";

function main(): void {
    const markdown = fs.readFileSync(SOURCE, "utf8");
    const fragments = parseFragments(markdown);
    if (fragments.length === 0) {
        throw new Error(`No fragments found in ${SOURCE}.`);
    }

    const snippets = toSnippets(fragments);
    const members = toMemberTable(fragments);

    fs.mkdirSync(path.dirname(SNIPPETS_OUT), { recursive: true });
    fs.writeFileSync(
        SNIPPETS_OUT,
        JSON.stringify({ ["//"]: BANNER, ...snippets }, null, 2) + "\n"
    );

    fs.mkdirSync(path.dirname(MEMBERS_OUT), { recursive: true });
    fs.writeFileSync(MEMBERS_OUT, renderMembers(members));

    const memberCount = Object.values(members).reduce((n, list) => n + list.length, 0);
    console.log(
        `${fragments.length} fragments → ${path.relative(ROOT, SNIPPETS_OUT)}, ` +
        `${memberCount} members across ${Object.keys(members).length} roots → ${path.relative(ROOT, MEMBERS_OUT)}`
    );
}

function renderMembers(members: Record<string, Member[]>): string {
    const lines: string[] = [
        `// ${BANNER}`,
        "",
        "export interface Member {",
        "    name: string;",
        '    kind: "method" | "property";',
        "}",
        "",
        "/** iLogic API roots that offer completions. */",
        `export const API_ROOTS = ${JSON.stringify(API_ROOTS)} as const;`,
        "",
        "/** Members observed on each API root, keyed by root. */",
        "export const MEMBERS: Record<string, readonly Member[]> = {",
    ];
    for (const [root, list] of Object.entries(members)) {
        lines.push(`    ${JSON.stringify(root)}: [`);
        for (const member of list) {
            lines.push(`        { name: ${JSON.stringify(member.name)}, kind: ${JSON.stringify(member.kind)} },`);
        }
        lines.push("    ],");
    }
    lines.push("};", "");
    return lines.join("\n");
}

main();
