// Canonical casing for VB.NET / iLogic keywords.
//
// Covers every reserved keyword in the VB language reference
// (learn.microsoft.com/dotnet/visual-basic/language-reference/keywords), cased
// as Roslyn writes them (Syntax.xml). Reserved words cannot be identifiers, so
// recasing them is always safe. Unreserved (contextual) keywords are included
// only where they are unlikely to be someone's variable name; Key, Text,
// Binary, Auto, Custom, Assembly, Mid and the LINQ words (From, Where, Group,
// Order, Join, ...) are left alone because a variable called "key" or "text"
// would otherwise be recased.
export const VB_KEYWORDS: Record<string, string> = {
    // Access modifiers
    public: "Public",
    private: "Private",
    protected: "Protected",
    friend: "Friend",
    // Declarations
    dim: "Dim",
    as: "As",
    new: "New",
    const: "Const",
    static: "Static",
    readonly: "ReadOnly",
    withevents: "WithEvents",
    shadows: "Shadows",
    overrides: "Overrides",
    overridable: "Overridable",
    mustoverride: "MustOverride",
    notoverridable: "NotOverridable",
    shared: "Shared",
    partial: "Partial",
    overloads: "Overloads",
    mustinherit: "MustInherit",
    notinheritable: "NotInheritable",
    default: "Default",
    writeonly: "WriteOnly",
    widening: "Widening",
    narrowing: "Narrowing",
    declare: "Declare",
    lib: "Lib",
    alias: "Alias",
    delegate: "Delegate",
    event: "Event",
    operator: "Operator",
    of: "Of",
    out: "Out",
    global: "Global",
    async: "Async",
    iterator: "Iterator",
    ansi: "Ansi",
    unicode: "Unicode",
    // Types
    boolean: "Boolean",
    byte: "Byte",
    sbyte: "SByte",
    short: "Short",
    ushort: "UShort",
    integer: "Integer",
    uinteger: "UInteger",
    long: "Long",
    ulong: "ULong",
    single: "Single",
    double: "Double",
    decimal: "Decimal",
    string: "String",
    char: "Char",
    date: "Date",
    object: "Object",
    nothing: "Nothing",
    true: "True",
    false: "False",
    // Control flow
    if: "If",
    then: "Then",
    else: "Else",
    elseif: "ElseIf",
    end: "End",
    endif: "End If",
    for: "For",
    each: "Each",
    in: "In",
    to: "To",
    step: "Step",
    next: "Next",
    while: "While",
    endwhile: "End While",
    do: "Do",
    loop: "Loop",
    until: "Until",
    select: "Select",
    case: "Case",
    endselect: "End Select",
    exit: "Exit",
    continue: "Continue",
    return: "Return",
    goto: "GoTo",
    call: "Call",
    stop: "Stop",
    yield: "Yield",
    await: "Await",
    redim: "ReDim",
    preserve: "Preserve",
    erase: "Erase",
    let: "Let",
    // Error handling
    try: "Try",
    catch: "Catch",
    finally: "Finally",
    endtry: "End Try",
    throw: "Throw",
    when: "When",
    // Sub / Function
    sub: "Sub",
    endsub: "End Sub",
    function: "Function",
    endfunction: "End Function",
    property: "Property",
    endproperty: "End Property",
    get: "Get",
    set: "Set",
    byval: "ByVal",
    byref: "ByRef",
    paramarray: "ParamArray",
    optional: "Optional",
    handles: "Handles",
    // OOP
    class: "Class",
    endclass: "End Class",
    interface: "Interface",
    endinterface: "End Interface",
    structure: "Structure",
    endstructure: "End Structure",
    enum: "Enum",
    endenum: "End Enum",
    module: "Module",
    endmodule: "End Module",
    namespace: "Namespace",
    endnamespace: "End Namespace",
    inherits: "Inherits",
    implements: "Implements",
    mybase: "MyBase",
    myclass: "MyClass",
    me: "Me",
    // Operators / misc
    and: "And",
    andalso: "AndAlso",
    or: "Or",
    orelse: "OrElse",
    not: "Not",
    xor: "Xor",
    is: "Is",
    isnot: "IsNot",
    like: "Like",
    mod: "Mod",
    typeof: "TypeOf",
    gettype: "GetType",
    directcast: "DirectCast",
    trycast: "TryCast",
    ctype: "CType",
    cint: "CInt",
    cdbl: "CDbl",
    cstr: "CStr",
    cbool: "CBool",
    cdec: "CDec",
    cdate: "CDate",
    cchar: "CChar",
    cbyte: "CByte",
    clng: "CLng",
    csng: "CSng",
    cobj: "CObj",
    cshort: "CShort",
    csbyte: "CSByte",
    cuint: "CUInt",
    culng: "CULng",
    cushort: "CUShort",
    addressof: "AddressOf",
    nameof: "NameOf",
    getxmlnamespace: "GetXmlNamespace",
    istrue: "IsTrue",
    isfalse: "IsFalse",
    addhandler: "AddHandler",
    removehandler: "RemoveHandler",
    raiseevent: "RaiseEvent",
    with: "With",
    endwith: "End With",
    using: "Using",
    endusing: "End Using",
    synclock: "SyncLock",
    endsynclock: "End SyncLock",
    imports: "Imports",
    option: "Option",
    strict: "Strict",
    explicit: "Explicit",
    compare: "Compare",
    infer: "Infer",
    off: "Off",
    on: "On",
    error: "Error",
    resume: "Resume",
    // Obsolete but still reserved
    gosub: "Gosub",
    variant: "Variant",
    wend: "Wend",
};
